sudo: required
services:
  - docker

before_install: 
  - docker build -t ratishnyaichyai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ratishnyaichyai/docker-react npm run test -- --coverage